name: Update project on issue closed
on:
  issues:
    types: [closed]

jobs:
  update_project_on_issue_close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          cd .github/actions/project_update/
          pip install -r requirements.txt

      - name: Update status and priority
        run: |
          cd .github/actions/project_update/
          python project_update.py ${{ github.event.issue.node_id }} --status Done
        env:
          MATHESAR_ORG_GITHUB_TOKEN: ${{secrets.MATHESAR_ORG_GITHUB_TOKEN}}
